# Generated by Django 4.0.5 on 2022-06-29 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_itenscompra_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='status',
            field=models.ForeignKey(default='Carrinho', on_delete=django.db.models.deletion.PROTECT, related_name='compra', to='core.statuscompra'),
        ),
    ]
