# Generated by Django 3.2.12 on 2022-06-29 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_compra_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='status',
            field=models.ForeignKey(default='Carrinjjjjjho', on_delete=django.db.models.deletion.PROTECT, related_name='compra', to='core.statuscompra'),
        ),
    ]
